@echo off
set GIT=C:\Users\muthu\AppData\Local\GitHubDesktop\app-3.5.8\resources\app\git\cmd\git.exe
echo Initializing git...
%GIT% init
echo Configuring user...
%GIT% config user.email "sheiknihar1016@gmail.com"
%GIT% config user.name "sheiknihar1016-web"
echo Adding files...
%GIT% add .
echo Committing...
%GIT% commit -m "first commit"
echo Setting branch...
%GIT% branch -M main
echo Adding remote...
%GIT% remote add origin https://github.com/sheiknihar1016-web/pokemon_ai.git
echo Pushing...
%GIT% push -u origin main
echo Done!
